version: '3.9'


services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: {user_username}
      POSTGRES_DB: {user_db}
      POSTGRES_PASSWORD: {user_password}
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"



volumes:
  postgres:
